use std::{env, fs, path::Path};

use anyhow::{Context, Result, bail};
use serde_json::{Value, json};

fn main() -> Result<()> {
    let mut args = env::args_os().skip(1);
    let input = args.next().context("missing OpenAPI input path")?;
    let output = args.next().context("missing generated output path")?;
    if args.next().is_some() {
        bail!("usage: octonomous-codegen <openapi.json> <generated.rs>");
    }

    let source = fs::read_to_string(&input)
        .with_context(|| format!("failed to read {}", Path::new(&input).display()))?;
    let mut document: Value = serde_json::from_str(&source).context("invalid OpenAPI JSON")?;
    normalize_for_progenitor(&mut document);

    let spec: openapiv3::OpenAPI =
        serde_json::from_value(document).context("normalized OpenAPI document is invalid")?;
    let tokens = progenitor::Generator::default()
        .generate_tokens(&spec)
        .context("Progenitor failed to generate the client")?;
    let syntax = syn::parse2(tokens).context("generated client is not valid Rust syntax")?;
    let generated = prettyplease::unparse(&syntax);
    let contents = format!(
        "// @generated by scripts/generate-client.sh; do not edit by hand.\n\
         // Source: docs/openapi-v2.0.18.json\n\n{generated}"
    );

    let output = Path::new(&output);
    fs::create_dir_all(output.parent().context("output path has no parent")?)?;
    fs::write(output, contents)
        .with_context(|| format!("failed to write {}", output.display()))?;
    Ok(())
}

fn normalize_for_progenitor(document: &mut Value) {
    normalize_schema(document);
    document["openapi"] = json!("3.0.3");

    // Progenitor currently requires one shared error type per operation. M2 owns
    // decoding the V2 `_tag` error envelope, so generated methods retain the
    // status and raw JSON body rather than choosing one incomplete error union.
    if let Some(paths) = document.get_mut("paths").and_then(Value::as_object_mut) {
        for path in paths.values_mut().filter_map(Value::as_object_mut) {
            for operation in path.values_mut().filter_map(Value::as_object_mut) {
                // An optional nullable header becomes Option<Option<T>> and
                // triggers invalid code in Progenitor 0.15. An omitted optional
                // header already represents the only useful null wire value.
                if let Some(parameters) = operation
                    .get_mut("parameters")
                    .and_then(Value::as_array_mut)
                {
                    for parameter in parameters.iter_mut().filter_map(Value::as_object_mut) {
                        if parameter.get("in") == Some(&json!("header"))
                            && parameter.get("required") != Some(&Value::Bool(true))
                            && let Some(schema) =
                                parameter.get_mut("schema").and_then(Value::as_object_mut)
                        {
                            schema.remove("nullable");
                        }
                    }
                }

                let Some(responses) = operation.get_mut("responses").and_then(Value::as_object_mut)
                else {
                    continue;
                };
                for (status, response) in responses {
                    if !status.starts_with('4') && !status.starts_with('5') {
                        continue;
                    }
                    let Some(content) = response
                        .get_mut("content")
                        .and_then(Value::as_object_mut)
                    else {
                        continue;
                    };
                    for media_type in content.values_mut().filter_map(Value::as_object_mut) {
                        media_type.insert("schema".into(), json!({}));
                    }
                }
            }
        }
    }

    // These unions overlap by construction, so no deserializer can determine
    // which branch authored a matching JSON string. Keep the wire value intact.
    if let Some(schemas) = document
        .pointer_mut("/components/schemas")
        .and_then(Value::as_object_mut)
    {
        for name in ["Form.Value", "Model.ReasoningField"] {
            schemas.insert(name.into(), json!({}));
        }
    }
}

fn normalize_schema(value: &mut Value) {
    match value {
        Value::Array(values) => values.iter_mut().for_each(normalize_schema),
        Value::Object(object) => {
            object.values_mut().for_each(normalize_schema);

            // OpenAPI 3.1 expresses nullability as `anyOf: [T, null]`; 3.0 uses
            // `nullable`. The pinned document only uses two-branch nullable
            // unions, so this conversion is lossless.
            if let Some(any_of) = object.get("anyOf").and_then(Value::as_array)
                && any_of.len() == 2
                && any_of.iter().filter(|item| item.get("type") == Some(&json!("null"))).count()
                    == 1
            {
                let mut replacement = any_of
                    .iter()
                    .find(|item| item.get("type") != Some(&json!("null")))
                    .and_then(Value::as_object)
                    .cloned()
                    .expect("non-null nullable branch must be an object");
                let siblings = std::mem::take(object);
                replacement.extend(siblings.into_iter().filter(|(key, _)| key != "anyOf"));
                replacement.insert("nullable".into(), Value::Bool(true));
                *object = replacement;
            }

            // OpenAPI 3.1 uses a numeric exclusive bound; 3.0 splits the bound
            // and exclusivity flag.
            if let Some(bound) = object.get("exclusiveMinimum").filter(|value| value.is_number()).cloned() {
                object.insert("minimum".into(), bound);
                object.insert("exclusiveMinimum".into(), Value::Bool(true));
            }

            // Progenitor does not implement deepObject parameters. Its normal
            // query serialization still exposes the operation; location wire
            // policy is applied by the handwritten client wrapper in M2.
            if object.get("style") == Some(&json!("deepObject")) {
                object.remove("style");
                object.remove("explode");
            }
        }
        _ => {}
    }
}
